"""Add a room table

Revision ID: 398b7648745
Revises: 7ca698e4768
Create Date: 2014-11-21 11:45:39.491000

"""

# revision identifiers, used by Alembic.
revision = '398b7648745'
down_revision = '7ca698e4768'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'posts', sa.Column('room_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'room_id')
    op.drop_table('rooms')
    ### end Alembic commands ###
