"""empty message

Revision ID: 4783093dd459
Revises: 4fc37a9c2738
Create Date: 2014-11-23 19:33:57.240000

"""

# revision identifiers, used by Alembic.
revision = '4783093dd459'
down_revision = '4fc37a9c2738'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spells', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('spells', sa.Column('purchased', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'purchased')
    op.drop_column('spells', 'approved')
    ### end Alembic commands ###
