"""Give tags a type column

Revision ID: 7ca698e4768
Revises: 10761add984c
Create Date: 2014-11-21 01:47:48.902000

"""

# revision identifiers, used by Alembic.
revision = '7ca698e4768'
down_revision = '10761add984c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('type', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'type')
    ### end Alembic commands ###
