"""empty message

Revision ID: 952e324ba37
Revises: 5121656bf9cd
Create Date: 2014-11-18 15:38:54.024000

"""

# revision identifiers, used by Alembic.
revision = '952e324ba37'
down_revision = '5121656bf9cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('students', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('students', 'password_hash')
    ### end Alembic commands ###
